#if !canImport(ObjectiveC)
import XCTest

extension AuthenticatorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AuthenticatorTests = [
        ("testMultipleRequestsForTokenAndRefreshedTokenAtTheSameTime", testMultipleRequestsForTokenAndRefreshedTokenAtTheSameTime),
        ("testMultipleRequestsForTokenAndRefreshedTokenAtTheSameTimeCallsTokenProviderOnlyOnce", testMultipleRequestsForTokenAndRefreshedTokenAtTheSameTimeCallsTokenProviderOnlyOnce),
        ("testReceivingTokenIsSuccessful", testReceivingTokenIsSuccessful),
        ("testRefreshedTokenReturnsNoValidTokenError", testRefreshedTokenReturnsNoValidTokenError),
        ("testRefreshedTokenReturnsSuccessfullyNewToken", testRefreshedTokenReturnsSuccessfullyNewToken),
        ("testTokenReturnsNoValidTokenError", testTokenReturnsNoValidTokenError),
        ("testTokenReturnsRefreshedTokenAfterNewTokenIsRefreshed", testTokenReturnsRefreshedTokenAfterNewTokenIsRefreshed),
    ]
}

extension CometTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CometTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AuthenticatorTests.__allTests__AuthenticatorTests),
        testCase(CometTests.__allTests__CometTests),
    ]
}
#endif
